version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15.7
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
